GameShop.Web/Areas/Admin/Controllers/PlatformController.cs
using GameShop.Data.Repository.IRepository;
using GameShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace GameShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PlatformController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PlatformController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Platform> platforms = _unitOfWork.Platform.GetAll();
            return View(platforms);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();  
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Platform platform)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Platform.Add(platform);
                _unitOfWork.Save();
                TempData["Success"] = "Platform created successfully.";
                return RedirectToAction("Index");
            }

            return View(platform);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _unitOfWork.Platform.GetFirstOrDefault(p => p.Id == id);
            if(category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Platform platform)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Platform.Update(platform);
                _unitOfWork.Save();
                TempData["Success"] = "Platform Edited Successfully.";
                return RedirectToAction("Index");
            }

            return View(platform);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            var platformToDelete = _unitOfWork.Platform.GetFirstOrDefault(p => p.Id == id);
            if(platformToDelete == null)
            {
                return NotFound();
            }

            return View(platformToDelete);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            var platformToDelete = _unitOfWork.Platform.GetFirstOrDefault(p => p.Id == id);
            if(platformToDelete == null)
            {
                return NotFound();
            }

            _unitOfWork.Platform.Remove(platformToDelete);
            _unitOfWork.Save();

            TempData["Success"] = "Platform Deleted Successfully.";
            return RedirectToAction("Index");
        }
    }
}

GameShop.Web/Areas/Admin/Views/Platform/Create.cshtml
@model Platform 

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Platform</h2>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Name"></label>
            <input asp-for="@Model.Name" class="form-control"/>
            <span asp-validation-for="@Model.Name" class="text-danger"></span> @*Server Side Validation*@
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button> 
            </div>
            <div class="col-6 text-end">
                <a asp-area="Admin" asp-controller="Platform" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
            </div>
        </div>
    </div>
</form>

@*Client Side Validation*@
@section Scripts{
    <partial name="_ValidationScriptsPartial"></partial>
}

GameShop.Web/Areas/Admin/Views/Platform/Delete.cshtml
@model Platform

<form method="post" asp-controller="Platform" asp-action="Delete">
    <input asp-for="Id" hidden/>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Platform</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled />
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Platform" asp-action="Index" class="btn btn-secondary" style="width:150px">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

GameShop.Web/Areas/Admin/Views/Platform/Edit.cshtml
@model Platform

<form method="post" asp-controller="Platform" asp-action="Edit">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Platform</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Platform" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
            </div>
        </div>
    </div>
</form> 

@*Client side validation*@
@section Scripts{
    <section name="_ValidationScriptsPartial"></section>
}

GameShop.Web/Areas/Admin/Views/Platform/Index.cshtml
@model IEnumerable<Platform>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row p4-4">
        <div class="col-6">
            <h2 class="text-primary">List of Platforms</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-area="Admin" asp-controller="Platform" asp-action="Create" class="btn btn-outline-light">
                <i class="bi bi-plus-circle-fill"></i> &nbsp; Create New Platform
            </a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Platform Name
            </th>
            <th>
                Edit
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var platform in Model)
        {
            <tr>
                <td width="50%">
                    @platform.Name
                </td>
                <td width="15%">
                    <div class="w-75 btn-group" role="group">
                            <a asp-area="Admin" asp-controller="Platform" asp-action="Edit" asp-route-id="@platform.Id" class="btn btn-info mx-4">
                                <i class="bi bi-pencil-square"></i> &nbsp; Edit
                            </a>
                            <a asp-area="Admin" asp-controller="Platform" asp-action="Delete" asp-route-id="@platform.Id" class="btn btn-danger mx-4">
                                <i class="bi bi-trash3"></i> &nbsp; Delete
                            </a>                   
                    </div>
                </td>
            </tr>    
        }
    </tbody>
</table>